# Generated by Django 3.2.6 on 2021-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="long_description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="short_description",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(to="games.Category"),
        ),
    ]
