project_id = "fireside-games"
terraform_service_account_key = "fireside-games-97119fb5b740.json.secret"
environment_file = "../../firesideweb/.env"
media_bucket_name = "fireside-games-django-media"
region = "asia-southeast1"
bucket_region = "asia-southeast1"
db_tier = "db-f1-micro"
db_name = "fireside-games-db"

support_email = "shirecoding@gmail.com"