# Generated by Django 4.0.5 on 2022-09-09 02:00

from django.db import migrations, models
import tasks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "fpath",
                    models.CharField(help_text="Path to import the function (eg. path.to.function)", max_length=256),
                ),
                (
                    "inputs",
                    models.JSONField(
                        default=tasks.models.default_inputs,
                        help_text="JSON containing the `args` and `kwargs` parameters for the function `fpath`",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
