# Generated by Django 4.0.5 on 2022-09-09 09:54

from django.db import migrations, models
import django.db.models.deletion
import tasks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskDefinition",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Name of this task definition", max_length=128)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "fpath",
                    models.CharField(
                        help_text="Path to the function to be run (eg. path.to.function)", max_length=256, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Name of this task", max_length=128)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "inputs",
                    models.JSONField(
                        default=tasks.models.default_task_inputs,
                        help_text="JSON containing the `args` and `kwargs` for `task`",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.taskdefinition"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
