# Generated by Django 4.0.5 on 2022-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="taskdefinition",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
