# Generated by Django 4.0.5 on 2022-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="fpath",
        ),
        migrations.AddField(
            model_name="task",
            name="task",
            field=models.CharField(
                choices=[("tasks.models.default_inputs", "Default Inputs (tasks.models.default_inputs)")],
                default="",
                max_length=128,
            ),
            preserve_default=False,
        ),
    ]
