# Generated by Django 4.0.5 on 2022-09-09 08:36

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_fpath_task_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="inputs",
            field=models.JSONField(
                default=tasks.models.default_inputs,
                help_text="JSON containing the `args` and `kwargs` parameters for the function `task`",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(help_text="Name of this task", max_length=128),
        ),
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(
                choices=[], help_text="Path to the function to be run (eg. path.to.function)", max_length=128
            ),
        ),
    ]
