# Generated by Django 4.0.5 on 2022-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_name_alter_taskdefinition_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When to activate model (If not set, model is considered activate as long as `now` < `deactivate_on`)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="deactivate_on",
            field=models.DateTimeField(
                blank=True, default=None, help_text="When to deactivate model."
            ),
            preserve_default=False,
        ),
    ]
