# Generated by Django 4.0.5 on 2022-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_activate_on_task_deactivate_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When to activate model (If not set, model is considered activate as long as `now` < `deactivate_on`)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deactivate_on",
            field=models.DateTimeField(
                blank=True, help_text="When to deactivate model.", null=True
            ),
        ),
    ]
