# Generated by Django 4.0.5 on 2022-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_inputs_alter_task_name_alter_task_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(
                choices=[("tasks.models.default_inputs", "Default Inputs (tasks.models.default_inputs)")],
                help_text="Path to the function to be run (eg. path.to.function)",
                max_length=128,
            ),
        ),
    ]
