# Generated by Django 4.0.5 on 2022-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_activate_on_alter_task_deactivate_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cron",
            field=models.CharField(
                blank=True,
                help_text="A cron string (e.g. '0 0 * * 0')",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat",
            field=models.IntegerField(
                blank=True,
                help_text="Repeat this number of times (None means repeat forever)",
                null=True,
            ),
        ),
    ]
