# Generated by Django 4.0.5 on 2022-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_cron_task_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("default", "Default"), ("high", "High")],
                default="default",
                help_text="Priority of the task",
                max_length=128,
            ),
        ),
    ]
