# Generated by Django 4.0.5 on 2022-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When to activate model (If None, model is considered activate as long as `now` < `deactivate_on`)",
                null=True,
            ),
        ),
    ]
