# Generated by Django 4.0.5 on 2022-09-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
