# Generated by Django 4.1.4 on 2022-12-23 12:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_room_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
