repos:
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black # config in pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2" # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: package-lock.json

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    additional_dependencies: [flake8-print]
    hooks:
      - id: flake8
