version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./deployments/Fireside.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    command: bash -c "cat /code/deployments/scripts/setup_docker_env.sh > ~/.bashrc && tail -f /dev/null"
