version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./deployments/Fireside.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: bash -c "cat /code/deployments/scripts/setup_docker_env.sh > ~/.bashrc && /code/firesideweb/manage.py runserver 0.0.0.0:8000"
