# Generated by Django 4.0.5 on 2022-10-08 09:57

from django.db import migrations, models
import django.db.models.deletion
import fireside.models.task
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskDefinition",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "fpath",
                    models.CharField(
                        help_text="Path to the function to be run (eg. path.to.function)",
                        max_length=256,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activate_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to activate model (If None, model is considered activate as long as `now` < `deactivate_on`)",
                        null=True,
                    ),
                ),
                (
                    "deactivate_on",
                    models.DateTimeField(
                        blank=True, help_text="When to deactivate model.", null=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "inputs",
                    models.JSONField(
                        default=fireside.models.task.default_task_inputs,
                        help_text="JSON containing the `args` and `kwargs` for `task`",
                    ),
                ),
                (
                    "cron",
                    models.CharField(
                        blank=True,
                        help_text="A cron string (e.g. '0 0 * * 0')",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "repeat",
                    models.IntegerField(
                        blank=True,
                        help_text="Repeat this number of times (None means repeat forever)",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("default", "Default"),
                            ("high", "High"),
                        ],
                        default="default",
                        help_text="Priority of the task",
                        max_length=128,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fireside.taskdefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
