# Generated by Django 4.1.4 on 2023-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskpreset",
            name="protocols",
        ),
        migrations.AddField(
            model_name="taskpreset",
            name="args",
            field=models.JSONField(
                blank=True, default=list, help_text="Input args for the task"
            ),
        ),
        migrations.AddField(
            model_name="taskpreset",
            name="kwargs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Input kwargs for the task"
            ),
        ),
    ]
