# Generated by Django 4.0.5 on 2022-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="taskdefinition",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
