# Generated by Django 4.1.4 on 2022-12-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpreset",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("default", "Default"), ("high", "High")],
                default="default",
                help_text="Priority of the task preset (overrides task priority)",
                max_length=128,
            ),
        ),
    ]
