# Generated by Django 4.1.4 on 2023-01-07 12:58

from django.db import migrations

import fireside.utils.fields.pydantic


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0002_remove_taskpreset_protocols_taskpreset_args_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskpreset",
            name="args",
            field=fireside.utils.fields.pydantic.PydanticField(
                blank=True, default=list, help_text="Input args for the task"
            ),
        ),
        migrations.AlterField(
            model_name="taskpreset",
            name="kwargs",
            field=fireside.utils.fields.pydantic.PydanticField(
                blank=True, default=dict, help_text="Input kwargs for the task"
            ),
        ),
    ]
