# Generated by Django 4.0.5 on 2022-10-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0002_alter_task_name_alter_taskdefinition_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="TaskSchedule",
        ),
    ]
