# Generated by Django 4.1.4 on 2022-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0002_taskpreset_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskpreset",
            name="event",
        ),
        migrations.AddField(
            model_name="taskpreset",
            name="protocols",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Preset protocols dictionary for the task",
            ),
        ),
    ]
