# Generated by Django 4.1.4 on 2022-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0003_remove_taskpreset_event_taskpreset_protocols"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskpreset",
            name="protocols",
            field=models.JSONField(
                blank=True, default=dict, help_text="Preset `ProtocolDict` for the task"
            ),
        ),
    ]
