# Generated by Django 4.1.4 on 2023-01-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0003_alter_taskpreset_args_alter_taskpreset_kwargs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskpreset",
            name="args",
        ),
    ]
