# Generated by Django 4.0.5 on 2022-10-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0003_rename_task_taskschedule"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskDefinition",
            new_name="Task",
        ),
    ]
