# Generated by Django 4.0.5 on 2022-10-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0004_rename_taskdefinition_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("default", "Default"), ("high", "High")],
                default="default",
                help_text="Priority of the task",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                help_text="Timeout of the task in seconds (leave empty to use the default timeout)",
                null=True,
            ),
        ),
    ]
