# Generated by Django 4.1.4 on 2023-01-13 11:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0005_alter_taskpreset_kwargs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "data_klass",
                    models.CharField(
                        help_text="Import path to the event data class (pydantic).",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventHandler",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "event_type",
                    models.CharField(
                        help_text="The event type which the event handler listens for.",
                        max_length=256,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="The task which will process the event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fireside.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
