# Generated by Django 4.0.5 on 2022-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0005_task_priority_task_timeout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskschedule",
            old_name="definition",
            new_name="task",
        ),
        migrations.RemoveField(
            model_name="taskschedule",
            name="description",
        ),
        migrations.RemoveField(
            model_name="taskschedule",
            name="name",
        ),
        migrations.AddField(
            model_name="taskschedule",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                help_text="Timeout of the task in seconds (leave empty to use the default timeout, overrides priority set in task)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskschedule",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("default", "Default"), ("high", "High")],
                default="default",
                help_text="Priority of the task (overrides priority set in task)",
                max_length=128,
            ),
        ),
    ]
