# Generated by Django 4.0.5 on 2022-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0006_rename_definition_taskschedule_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskschedule",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the model is considered activated (If None, model is considered activate as long as `now` < `deactivate_on`)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskschedule",
            name="deactivate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the model is considered deactivated.",
                null=True,
            ),
        ),
    ]
