# Generated by Django 4.0.5 on 2022-12-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0007_alter_taskschedule_activate_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskChain",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fireside.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("fireside.task",),
        ),
        migrations.CreateModel(
            name="TaskOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Order of the tasks in a chain"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="fireside.task",
                    ),
                ),
                (
                    "task_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="fireside.taskchain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskchain",
            name="tasks",
            field=models.ManyToManyField(
                related_name="+", through="fireside.TaskOrder", to="fireside.task"
            ),
        ),
    ]
