# Generated by Django 4.1.4 on 2023-01-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0007_remove_eventhandler_event_type_eventhandler_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="data_klass",
        ),
        migrations.AddField(
            model_name="event",
            name="tpath",
            field=models.CharField(
                default="",
                help_text="Import path of the type class of the event.",
                max_length=256,
            ),
            preserve_default=False,
        ),
    ]
