# Generated by Django 4.1.4 on 2023-01-14 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0008_remove_event_data_klass_event_tpath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tpath",
        ),
        migrations.AlterField(
            model_name="eventhandler",
            name="event",
            field=models.ForeignKey(
                help_text="The event which the event handler listens for.",
                on_delete=django.db.models.deletion.CASCADE,
                to="fireside.event",
            ),
        ),
    ]
