# Generated by Django 4.0.5 on 2022-12-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0008_taskchain_taskorder_taskchain_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskorder",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fireside.task"
            ),
        ),
    ]
