# Generated by Django 4.0.5 on 2022-12-17 03:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0009_alter_taskorder_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPreset",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(default="", max_length=256)),
                (
                    "input_event",
                    models.JSONField(
                        default=dict, help_text="Preset input event for the task"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fireside.task"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="taskorder",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskorder",
            name="task_chain",
        ),
        migrations.DeleteModel(
            name="TaskChain",
        ),
        migrations.DeleteModel(
            name="TaskOrder",
        ),
    ]
