# Generated by Django 4.0.5 on 2022-12-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0010_taskpreset_remove_taskorder_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskpreset",
            name="input_event",
        ),
        migrations.AddField(
            model_name="taskpreset",
            name="event",
            field=models.JSONField(default=dict, help_text="Preset event for the task"),
        ),
    ]
