# Generated by Django 4.0.5 on 2022-12-17 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0011_remove_taskpreset_input_event_taskpreset_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskschedule",
            name="inputs",
        ),
        migrations.RemoveField(
            model_name="taskschedule",
            name="task",
        ),
        migrations.AddField(
            model_name="taskpreset",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the model is considered activated (If None, model is considered activate as long as `now` < `deactivate_on`)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskpreset",
            name="deactivate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the model is considered deactivated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskschedule",
            name="task_preset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fireside.taskpreset",
            ),
            preserve_default=False,
        ),
    ]
