# Generated by Django 4.0.5 on 2022-12-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fireside",
            "0012_remove_taskschedule_inputs_remove_taskschedule_task_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskpreset",
            name="event",
            field=models.JSONField(
                blank=True, default=dict, help_text="Preset event for the task"
            ),
        ),
    ]
