# Generated by Django 4.1.5 on 2023-04-01 11:05

from django.db import migrations, models

import fireside.utils.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0013_tasklog_result_tasklog_traceback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="fpath",
            field=models.CharField(
                help_text="Path to the function to be run (eg. path.to.function).",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                help_text="Timeout of the task in seconds (leave empty to use the default timeout).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskpreset",
            name="kwargs",
            field=fireside.utils.fields.json.JSONField(
                blank=True, default=dict, help_text="Input kwargs for the `task`."
            ),
        ),
        migrations.AlterField(
            model_name="taskpreset",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("default", "Default"), ("high", "High")],
                default="default",
                help_text="Priority of the task preset (overrides task priority).",
                max_length=128,
            ),
        ),
    ]
