# Generated by Django 4.1.5 on 2023-04-07 10:01

from django.db import migrations

import fireside.utils.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0014_alter_task_fpath_alter_task_timeout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpreset",
            name="args",
            field=fireside.utils.fields.json.JSONField(
                blank=True, default=list, help_text="Input args for the `task`."
            ),
        ),
    ]
