# Generated by Django 4.1.5 on 2023-04-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside", "0015_taskpreset_args"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskpreset",
            name="args",
            field=models.JSONField(
                blank=True, default=list, help_text="Input args for the `task`."
            ),
        ),
    ]
