# Generated by Django 4.0.5 on 2022-08-14 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicShipModel",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="Basic", help_text="Ship type.", max_length=255
                    ),
                ),
                ("name", models.CharField(help_text="Ship name.", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
