# Generated by Django 4.0.5 on 2022-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireside_tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicshipmodel",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When to activate model (If not set, model is considered activate as long as `now` < `deactivate_on`)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="basicshipmodel",
            name="deactivate_on",
            field=models.DateTimeField(blank=True, help_text="When to deactivate model.", null=True),
        ),
    ]
