version: "3.9"
services:
  # postgres
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # redis
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "${CACHE_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASSWORD}
    volumes:
      - cache:/data

  # scheduler
  scheduler:
    build:
      context: .
      dockerfile: Fireside.Dockerfile
    restart: always
    depends_on:
      - cache
    command: bash -c "rqscheduler --host cache --port ${CACHE_PORT} --password ${CACHE_PASSWORD}"

volumes:
  db:
    driver: local
  cache:
    driver: local
