version: "3.9"
services:
  # postgres
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # redis
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "${CACHE_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASSWORD}
    volumes:
      - cache:/data

  # rq scheduler
  scheduler:
    build:
      context: .
      dockerfile: Fireside.Dockerfile
    restart: always
    depends_on:
      - cache
    volumes:
      - ./:/app
      - ./.env.docker:/app/.env
    command: bash -c "/app/manage.py rqscheduler"

  # rq worker
  worker:
    build:
      context: .
      dockerfile: Fireside.Dockerfile
    restart: always
    depends_on:
      - cache
    volumes:
      - ./:/app
      - ./.env.docker:/app/.env
    command: bash -c "/app/manage.py rqworker high default low"

volumes:
  db:
    driver: local
  cache:
    driver: local
