version: "3.9"
services:
  # postgres
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # redis
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "${CACHE_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASSWORD}
    volumes:
      - cache:/data

  # rq scheduler
  scheduler:
    build:
      context: .
      dockerfile: Fireside.Dockerfile
    restart: always
    depends_on:
      - cache
    volumes:
      - ./:/app
      - ./.env:/app/.env
    environment:
      DB_HOST: db
      CACHE_HOST: cache
    command: bash -c "/app/manage.py rqscheduler"

  # rq worker
  worker:
    build:
      context: .
      dockerfile: Fireside.Dockerfile
    restart: always
    depends_on:
      - cache
    volumes:
      - ./:/app
      - ./.env:/app/.env
    environment:
      DB_HOST: db
      CACHE_HOST: cache
    command: bash -c "/app/manage.py rqworker high default low"

  # django
  django:
    build:
      context: .
      dockerfile: Fireside.Dockerfile
    restart: always
    depends_on:
      - db
      - cache
      - scheduler
      - worker
    volumes:
      - ./:/app
      - ./.env:/app/.env
    ports:
      - "${WEB_PORT}:8000"
    environment:
      DB_HOST: db
      CACHE_HOST: cache
      DJANGO_SETTINGS_MODULE: core.settings
    command: bash -c "/app/manage.py bootstrap ; /app/manage.py runserver 0.0.0.0:8000"
    # command: bash -c "/app/manage.py bootstrap ; uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload"  # don't use --reload on production

volumes:
  db:
    driver: local
  cache:
    driver: local
