# Generated by Django 3.2.6 on 2021-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="games.Category"),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="game",
            name="long_description",
            field=models.TextField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="game",
            name="short_description",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
