# Generated by Django 3.2.6 on 2021-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_auto_20211217_2225"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="websocket",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
