# Generated by Django 3.2.6 on 2021-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_auto_20210911_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="long_description",
            field=models.TextField(max_length=500),
        ),
    ]
