# Generated by Django 3.2.6 on 2021-11-18 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="long_description",
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="short_description",
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name="GameInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="games.game",
                    ),
                ),
            ],
        ),
    ]
