# Generated by Django 3.2.6 on 2021-11-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_auto_20211118_2213"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
