# Generated by Django 3.2.6 on 2021-11-30 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profile_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilesettings",
            name="settings",
            field=models.JSONField(
                default={}, help_text="User profile settings in JSON or YAML format."
            ),
        ),
        migrations.AlterField(
            model_name="userprofilesettings",
            name="about",
            field=models.TextField(default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="userprofilesettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
