# Generated by Django 3.2.6 on 2021-11-30 14:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0006_alter_category_options"),
        ("profile_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofilesettings",
            options={"verbose_name_plural": "user profile settings"},
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="settings",
            field=models.JSONField(
                default=dict, help_text="User profile settings in JSON or YAML format."
            ),
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="title",
            field=models.CharField(default="Initiate", max_length=256),
        ),
        migrations.AlterField(
            model_name="userprofilesettings",
            name="about",
            field=models.TextField(default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="userprofilesettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GameMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow,
                        help_text="The datetime the user created an account for the game.",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow,
                        help_text="The last datetime the user played the game.",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_memberships",
                        to="games.game",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_memberships",
                        to="profile_settings.userprofilesettings",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="games",
            field=models.ManyToManyField(
                through="profile_settings.GameMembership", to="games.Game"
            ),
        ),
    ]
