# Generated by Django 3.2.6 on 2021-12-01 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0002_auto_20211130_2214"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow,
                        help_text="The datetime this connection was created.",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        default="",
                        help_text="Type of the connection (Friend, ...)",
                        max_length=256,
                    ),
                ),
                (
                    "connection_state",
                    models.CharField(
                        default="",
                        help_text="State of the connection (Accepted, Request, ...)",
                        max_length=256,
                    ),
                ),
                (
                    "other_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_settings.userprofilesettings",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_connections",
                        to="profile_settings.userprofilesettings",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="connections",
            field=models.ManyToManyField(
                related_name="_profile_settings_userprofilesettings_connections_+",
                through="profile_settings.UserConnection",
                to="profile_settings.UserProfileSettings",
            ),
        ),
    ]
