# Generated by Django 3.2.6 on 2021-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0003_auto_20211201_2109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconnection",
            name="connection_state",
            field=models.CharField(
                choices=[("Request", "Request"), ("Accepted", "Accepted")],
                default="Request",
                help_text="State of the connection (Accepted, Request, ...)",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="userconnection",
            name="connection_type",
            field=models.CharField(
                choices=[("Friend", "Friend")],
                default="Friend",
                help_text="Type of the connection (Friend, ...)",
                max_length=256,
            ),
        ),
    ]
