# Generated by Django 3.2.6 on 2021-12-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0004_auto_20211201_2125"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilesettings",
            name="color_theme",
            field=models.CharField(
                choices=[
                    ("#173F5F", "p1_darkblue"),
                    ("#20639B", "p1_blue"),
                    ("#3CAEA3", "p1_green"),
                    ("#F6D55C", "p1_yellow"),
                    ("#ED553B", "p1_red"),
                ],
                default="#173F5F",
                max_length=16,
            ),
        ),
    ]
