# Generated by Django 3.2.6 on 2021-12-01 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profile_settings", "0005_userprofilesettings_color_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow,
                        help_text="The datetime this mail was created.",
                    ),
                ),
                ("title", models.TextField(default="", max_length=128)),
                ("content", models.TextField(default="", max_length=4096)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_mail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofilesettings",
            name="mail",
            field=models.ManyToManyField(to="profile_settings.Mail"),
        ),
    ]
