# Generated by Django 3.2.6 on 2021-12-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0006_auto_20211201_2247"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_mail",
                to="profile_settings.userprofilesettings",
            ),
        ),
    ]
