# Generated by Django 3.2.6 on 2021-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0007_mail_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
    ]
