# Generated by Django 3.2.6 on 2021-12-07 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0008_alter_mail_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamemembership",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The datetime the user created an account for the game.",
            ),
        ),
        migrations.AlterField(
            model_name="gamemembership",
            name="last_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The last datetime the user played the game.",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The datetime this mail was created.",
            ),
        ),
        migrations.AlterField(
            model_name="userconnection",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The datetime this connection was created.",
            ),
        ),
    ]
