# Generated by Django 3.2.6 on 2021-12-17 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The datetime the user created an account for the game.",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The last datetime the user played the game.",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The datetime this mail was created.",
                    ),
                ),
                ("title", models.CharField(default="", max_length=128)),
                ("content", models.TextField(default="", max_length=4096)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_mail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The last datetime of any user activity.",
                    ),
                ),
                ("about", models.TextField(blank=True, default="", max_length=4096)),
                ("title", models.CharField(default="Initiate", max_length=256)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User profile in JSON or YAML format.",
                    ),
                ),
                (
                    "color_theme",
                    models.CharField(
                        choices=[
                            ("#173F5F", "p1_darkblue"),
                            ("#20639B", "p1_blue"),
                            ("#3CAEA3", "p1_green"),
                            ("#F6D55C", "p1_yellow"),
                            ("#ED553B", "p1_red"),
                        ],
                        default="#173F5F",
                        max_length=16,
                    ),
                ),
                (
                    "games",
                    models.ManyToManyField(
                        through="user_profile.GameMembership", to="games.Game"
                    ),
                ),
                ("mail", models.ManyToManyField(to="user_profile.Mail")),
            ],
        ),
        migrations.CreateModel(
            name="UserRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The datetime this connection was created.",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[("Friend", "Friend")],
                        default="Friend",
                        help_text="Type of the connection (Friend, ...)",
                        max_length=256,
                    ),
                ),
                (
                    "relationship_state",
                    models.CharField(
                        choices=[("Request", "Request"), ("Accepted", "Accepted")],
                        default="Request",
                        help_text="State of the connection (Accepted, Request, ...)",
                        max_length=256,
                    ),
                ),
                (
                    "other_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_relationships",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="relationships",
            field=models.ManyToManyField(
                related_name="_user_profile_userprofile_relationships_+",
                through="user_profile.UserRelationship",
                to="user_profile.UserProfile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sessions.session",
            ),
        ),
        migrations.AddField(
            model_name="mail",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_mail",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="gamemembership",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="user_profile.userprofile",
            ),
        ),
    ]
