# Generated by Django 3.2.6 on 2021-12-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamemembership",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_memberships",
                to="user_profile.userprofile",
            ),
        ),
    ]
