# Generated by Django 3.2.6 on 2022-01-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_gamemembership_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrelationship",
            unique_together={("user_profile", "other_profile")},
        ),
    ]
